Move hive init scripts
centos -> default
default -> debian

This assumes that "default" is platform_family == rhel rather than debian

diff --git a/templates/default/hive-metastore.erb b/templates/default/hive-metastore.erb
--- a/templates/default/hive-metastore.erb
+++ b/templates/default/hive-metastore.erb
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 #
 # Licensed to the Apache Software Foundation (ASF) under one or more
 # contributor license agreements.  See the NOTICE file distributed with
@@ -14,40 +14,30 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-
-# skeleton  example file to build /etc/init.d/ scripts.
-#    This file should be used to construct scripts for /etc/init.d.
 #
-#    Written by Miquel van Smoorenburg <miquels@cistron.nl>.
-#    Modified for Debian
-#    by Ian Murdock <imurdock@gnu.ai.mit.edu>.
-#               Further changes by Javier Fernandez-Sanguino <jfs@debian.org>
-#
-# Starts a Hive metastore
+# Starts a Hive Metastore
 #
 # chkconfig: 345 85 15
-# description: Starts a Hive metastore
-# processname: hive
+# description: Hive Metastore
 #
 ### BEGIN INIT INFO
 # Provides:          hive-metastore
-# Required-Start:    $syslog $remote_fs
-# Should-Start:
-# Required-Stop:     $syslog $remote_fs
-# Should-Stop:
+# Short-Description: Hive Metastore
 # Default-Start:     3 4 5
 # Default-Stop:      0 1 2 6
-# Short-Description: Starts a Hive metastore
+# Required-Start:    $syslog $remote_fs
+# Required-Stop:     $syslog $remote_fs
+# Should-Start:
+# Should-Stop:
 ### END INIT INFO
 
-source /lib/lsb/init-functions
+. /lib/lsb/init-functions
+BIGTOP_DEFAULTS_DIR=${BIGTOP_DEFAULTS_DIR-/etc/default}
+[ -n "${BIGTOP_DEFAULTS_DIR}" -a -r ${BIGTOP_DEFAULTS_DIR}/hadoop ] && . ${BIGTOP_DEFAULTS_DIR}/hadoop
+[ -n "${BIGTOP_DEFAULTS_DIR}" -a -r ${BIGTOP_DEFAULTS_DIR}/hive-metastore ] && . ${BIGTOP_DEFAULTS_DIR}/hive-metastore
 
 # Autodetect JAVA_HOME if not defined
-if [ -e /usr/libexec/bigtop-detect-javahome ]; then
-  . /usr/libexec/bigtop-detect-javahome
-elif [ -e /usr/lib/bigtop-utils/bigtop-detect-javahome ]; then
-  . /usr/lib/bigtop-utils/bigtop-detect-javahome
-fi
+. /usr/lib/bigtop-utils/bigtop-detect-javahome
 
 RETVAL_SUCCESS=0
 
@@ -55,115 +45,140 @@ STATUS_RUNNING=0
 STATUS_DEAD=1
 STATUS_DEAD_AND_LOCK=2
 STATUS_NOT_RUNNING=3
-STATUS_DEBIAN_NOT_RUNNING=4
+STATUS_OTHER_ERROR=102
+
 
 ERROR_PROGRAM_NOT_INSTALLED=5
 ERROR_PROGRAM_NOT_CONFIGURED=6
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-NAME="hive-metastore"
-DESC="Hive metastore daemon"
-SYS_FILE="/etc/default/${NAME}"
-EXE_FILE="/usr/lib/hive/bin/hive"
-PID_FILE="/var/run/hive/${NAME}.pid"
-LOCKFILE="/var/lock/${NAME}"
-LOG_FILE="/var/log/hive/${NAME}.log"
-HIVE_USER="hive"
-HIVE_HOME="`eval echo ~$HIVE_USER`"
-NICENESS="+0"
-TIMEOUT=3
-
-[ -f $SYS_FILE ] && . $SYS_FILE
-
-hive_start() {
-    [ -x $EXE_FILE ] || exit $ERROR_PROGRAM_NOT_INSTALLED
-
-    exec_env="HADOOP_OPTS=\"-Dhive.log.dir=`dirname $LOG_FILE` -Dhive.log.file=${NAME}.log -Dhive.log.threshold=INFO\""
-    service_name="metastore"
-    if [ $service_name = "server" ] ; then
-      service_name="hiveserver"
-    fi
-
-    log_success_msg "Starting $desc (${NAME}): "
-    /sbin/start-stop-daemon --quiet --oknodo --start --user $HIVE_USER --name java --background \
-       --chuid $HIVE_USER --nicelevel $NICENESS --chdir $HIVE_HOME \
-       --make-pidfile --pidfile $PID_FILE --startas /bin/sh -- \
-       -c "$exec_env exec $EXE_FILE --service $service_name $PORT > $LOG_FILE 2>&1 < /dev/null"
-
-    RETVAL=$?
-    [ $RETVAL -eq $RETVAL_SUCCESS ] && touch $LOCKFILE
-    return $RETVAL
-}
-
-hive_stop() {
-    log_success_msg "Stopping $desc (${NAME}): "
-    killproc -p $PID_FILE java
-    RETVAL=$?
-
-    [ $RETVAL -eq $RETVAL_SUCCESS ] && rm -f $LOCKFILE $PID_FILE
-    return $RETVAL
-}
-
-hive_restart() {
-    hive_stop
-    [ -n "$TIMEOUT" ] && sleep $TIMEOUT
-    hive_start
-}
-
-hive_status() {
-    echo -n "Checking for service $desc: "
-    pidofproc -p $PID_FILE java > /dev/null
-    RETVAL=$?
-
-    case "$RETVAL" in
-      $STATUS_RUNNING)
-        log_success_msg "metastore is running"
-        ;;
-      $STATUS_DEAD)
-        log_failure_msg "metastore is dead and pid file exists"
-        ;;
-      $STATUS_DEAD_AND_LOCK)
-        log_failure_msg "metastore is dead and lock file exists"
-        ;;
-      $STATUS_NOT_RUNNING|$STATUS_DEBIAN_NOT_RUNNING)
-        log_failure_msg "metastore is not running"
-        ;;
-      *)
-        log_failure_msg "metastore status is unknown"
-        ;;
-    esac
-    return $RETVAL
-}
 
 RETVAL=0
+SLEEP_TIME=5
+PROC_NAME="java"
 
-case "$1" in
-    start)
-      hive_start
+DAEMON="hive-metastore"
+DESC="Hive Metastore"
+EXEC_PATH="/usr/lib/hive/bin/hive"
+SVC_USER="hive"
+DAEMON_FLAGS=""
+CONF_DIR="/etc/hive/conf"
+PIDFILE="/var/run/hive/hive-metastore.pid"
+LOCKDIR="/var/lock/subsys"
+LOCKFILE="$LOCKDIR/hive-metastore"
+WORKING_DIR="/var/lib/hive"
+
+install -d -m 0755 -o hive -g hive /var/run/hive 1>/dev/null 2>&1 || :
+[ -d "$LOCKDIR" ] || install -d -m 0755 $LOCKDIR 1>/dev/null 2>&1 || :
+start() {
+    [ -x $EXE_FILE ] || exit $ERROR_PROGRAM_NOT_INSTALLED
+    log_success_msg "Starting $DESC (${DAEMON}): "
+
+    checkstatusofproc
+    status=$?
+    if [ "$status" -eq "$STATUS_RUNNING" ]; then
+        log_success_msg "${DESC} is running"
+        exit 0
+    fi
+
+    LOG_FILE=/var/log/hive/${DAEMON}.out
+
+    exec_env="HADOOP_OPTS=\"-Dhive.log.dir=`dirname $LOG_FILE` -Dhive.log.file=${DAEMON}.log -Dhive.log.threshold=INFO\""
+
+    # Autodetect JDBC drivers for metastore
+    . /usr/lib/bigtop-utils/bigtop-detect-classpath
+    exec_env="HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:${BIGTOP_CLASSPATH} $exec_env"
+
+    su -s /bin/bash $SVC_USER -c "$exec_env nohup nice -n 0 \
+        $EXEC_PATH --service metastore $PORT \
+            > $LOG_FILE 2>&1 < /dev/null & "'echo $! '"> $PIDFILE"
+    sleep 3
+
+    checkstatusofproc
+    RETVAL=$?
+    [ $RETVAL -eq $STATUS_RUNNING ] && touch $LOCKFILE
+    return $RETVAL
+}
+stop() {
+    log_success_msg "Stopping $DESC (${DAEMON}): "
+    killproc -p $PIDFILE java
+    RETVAL=$?
+
+    [ $RETVAL -eq $RETVAL_SUCCESS ] && rm -f $LOCKFILE $PIDFILE
+    return $RETVAL
+}
+restart() {
+  stop
+  start
+}
+
+checkstatusofproc(){
+  pidofproc -p $PIDFILE $PROC_NAME > /dev/null
+}
+
+checkstatus(){
+  checkstatusofproc
+  status=$?
+
+  case "$status" in
+    $STATUS_RUNNING)
+      log_success_msg "${DESC} is running"
       ;;
-
-    stop|force-stop)
-      hive_stop
-      ;; 
-
-    force-reload|condrestart|try-restart)
-      [ -e $LOCKFILE ] && hive_restart || :
+    $STATUS_DEAD)
+      log_failure_msg "${DESC} is dead and pid file exists"
       ;;
-
-    restart|reload)
-      hive_restart
+    $STATUS_DEAD_AND_LOCK)
+      log_failure_msg "${DESC} is dead and lock file exists"
       ;;
-  
-    status)
-      hive_status
+    $STATUS_NOT_RUNNING)
+      log_failure_msg "${DESC} is not running"
       ;;
-
     *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|restart|reload|condrestart|try-restart|force-reload|status|force-stop}" >&2
+      log_failure_msg "${DESC} status is unknown"
+      ;;
+  esac
+  return $status
+}
 
-	exit 1
-	;;
-esac
+condrestart(){
+  [ -e $LOCKFILE ] && restart || :
+}
+
+check_for_root() {
+  if [ $(id -ur) -ne 0 ]; then
+    echo 'Error: root user required'
+    echo
+    exit 1
+  fi
+}
+
+service() {
+  case "$1" in
+    start)
+      check_for_root
+      start
+      ;;
+    stop)
+      check_for_root
+      stop
+      ;;
+    status)
+      checkstatus
+      RETVAL=$?
+      ;;
+    restart)
+      check_for_root
+      restart
+      ;;
+    condrestart|try-restart)
+      check_for_root
+      condrestart
+      ;;
+    *)
+      echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
+      exit 1
+  esac
+}
+
+service "$1"
 
 exit $RETVAL
